// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWqj9GIi7yPdgcBtH5McFRuoWn3-MercY',
    appId: '1:831632114120:android:0e4f88a8853ed53d5e00fd',
    messagingSenderId: '831632114120',
    projectId: 'nearbyhungry-6a1ab',
    storageBucket: 'nearbyhungry-6a1ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVgzmUREaOZn7MRdqL2Ke-5F3zJIJo7M',
    appId: '1:831632114120:ios:61b947a283ffdfa45e00fd',
    messagingSenderId: '831632114120',
    projectId: 'nearbyhungry-6a1ab',
    storageBucket: 'nearbyhungry-6a1ab.firebasestorage.app',
    androidClientId:
    '831632114120-81j3qpv7175jeeu4mjqte4ccfhpmcsld.apps.googleusercontent.com',
    iosClientId:
    '831632114120-hsqfmsjh7inl1jnuqrju4tuuf5t4e1ni.apps.googleusercontent.com',
    iosBundleId: 'com.vishal.nearbyhungry',
  );
}