// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWqj9GIi7yPdgcBtH5McFRuoWn3-MercY',
    appId: '1:831632114120:android:6ec55afa61234d855e00fd',
    messagingSenderId: '831632114120',
    projectId: 'nearbyhungry-6a1ab',
    storageBucket: 'nearbyhungry-6a1ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVgzmUREaOZn7MRdqL2Ke-5F3zJIJo7M',
    appId: '1:831632114120:ios:814e57a1fd1142d95e00fd',
    messagingSenderId: '831632114120',
    projectId: 'nearbyhungry-6a1ab',
    storageBucket: 'nearbyhungry-6a1ab.firebasestorage.app',
    androidClientId: '831632114120-81j3qpv7175jeeu4mjqte4ccfhpmcsld.apps.googleusercontent.com',
    iosClientId: '831632114120-ceqon1007ls0ajuss1k6c4lp15tvbbls.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbyHungryFlutter',
  );
}
